const booking='https://aknailsspa.getrichbooking.com';
const path=location.pathname;const page=path.includes('service')?'service':path.includes('gallery')?'gallery':path.includes('contact')?'contact':'home';
const book=`<a class="book" href="${booking}" target="_blank" rel="noopener">Book Now</a>`;
const galleryItems=[
['nails-hero.png','The nude edit','Soft blush · champagne gold','Nude blush almond nails with delicate gold accents'],
['nails-brown.png','Chocolate atelier','Brown ombre · modern French','Chocolate brown French and ombre almond nails'],
['nails-floral.png','Petal & polish','Blush petals · sculpted detail','Blush nails with sculpted flowers and gold detail'],
['nails-pearl.png','Pearl whisper','Blush French · pearl chrome','Nude almond nails with blush French and pearl chrome'],
['nails-marble.png','Marble muse','Chocolate marble · fine gold','Chocolate and beige marble almond nail design']
];
const gallery=`<div class="gallery-shell"><div class="gallery-controls"><span>Swipe or scroll to explore</span><div><button class="gallery-prev" aria-label="Previous nail designs">Previous</button><button class="gallery-next" aria-label="Next nail designs">Next</button></div></div><div class="gallery-grid" tabindex="0" role="region" aria-label="Scrollable nail inspiration gallery">${galleryItems.map(([file,title,sub,alt])=>`<figure class="art-card"><button class="art-image" data-title="${title}" aria-label="Enlarge ${title}"><img src="/assets/${file}" alt="${alt}" loading="lazy"></button><figcaption><strong>${title}</strong><small>${sub}</small></figcaption></figure>`).join('')}</div></div>`;
const serviceImages={pedicures:['spa-pedicure.png'],manicures:['nails-pearl.png','nails-hero.png'],enhancements:['nails-brown.png','nails-marble.png','nails-floral.png'],addons:['nails-floral.png','nails-marble.png','nails-pearl.png'],kids:['nails-pearl.png'],waxing:['waxing.png']};
const intro=(tag,title,copy)=>`<section class="page-intro"><p class="eyebrow">${tag}</p><h1>${title}</h1><p>${copy}</p></section>`;
const home=`<section class="hero"><div class="hero-copy"><p class="eyebrow">AK Nails & Spa · Wilmington, DE</p><h1>Beauty in<br>every <em>detail.</em></h1><p>Express your style. Settle into a little relaxation. Leave feeling like you.</p>${book}<div class="hero-meta">BEAUTY &nbsp;·&nbsp; RELAX &nbsp;·&nbsp; CONFIDENCE</div></div><div class="hero-photo"><img src="/assets/nails-hero.png" alt="Elegant nude and gold nail design inspiration" fetchpriority="high"><span class="photo-caption">The nude edit · design inspiration</span></div></section><div class="ticker" aria-hidden="true"><div>${Array(4).fill('<span>NAIL ART</span>✦<span>SPA PEDICURES</span>✦<span>YOUR MOMENT</span>✦<span>AK NAILS & SPA</span>✦').join('')}</div></div><section class="section"><div class="section-head reveal"><div><p class="eyebrow">The service edit</p><h2>Your style.<br>Your <em>ritual.</em></h2></div><a class="text-link" href="/service/">Explore all services</a></div><div class="service-grid"><article class="service-tile reveal"><span class="number">01 / NAILS</span><h3>Manicures & enhancements</h3><p>From fresh gel color to acrylic, Polygel, and Gel-X extensions.</p><a class="text-link" href="/service/#enhancements">Find your finish</a></article><article class="service-tile reveal"><span class="number">02 / RELAX</span><h3>The pedicure collection</h3><p>Warm towels, hot stones, and spa rituals that give you time to unwind.</p><a class="text-link" href="/service/#pedicures">Choose your ritual</a></article><article class="service-tile reveal"><span class="number">03 / DETAILS</span><h3>Art that feels like you</h3><p>Soft neutrals, modern shapes, and expressive details for your next set.</p><a class="text-link" href="/gallery/">Explore the art gallery</a></article></div></section><section class="section dark"><div class="section-head reveal"><div><p class="eyebrow">Art gallery</p><h2>A little polish.<br>A lot of <em>personality.</em></h2></div><p>Explore our AI-created design inspiration, then bring your favorites to your appointment.</p></div>${gallery}<a class="text-link" style="display:inline-block;margin-top:30px" href="/gallery/">View the gallery</a></section><section class="section ritual"><div class="reveal"><img src="/assets/logo-champagne.png" alt="AK Nails & Spa gold logo: Beauty, Relax, Confidence" loading="lazy"></div><div class="reveal"><p class="eyebrow">The signature experience</p><h2>Make time<br>for <em>yourself.</em></h2><p>Our AK Nails Signature Spa Pedicure brings together fresh lemon, lemongrass, ginger, and rose petals, Glow Spa Collagen care, warm towels, hot stones, and a soothing massage candle.</p><p>Enjoy a 20-minute foot and lower-leg massage plus a 5-minute hand massage.</p><div class="price">$95 <small style="font-size:14px;color:var(--muted)">cash · $96.90 card</small></div>${book}</div></section>`;
const menus=[['pedicures','Pedicure collection',[
['Regular Pedicure',38,'Foot soak, nail shaping, cuticle care, heel smoothing, light massage, and regular polish.'],['Gel Pedicure',50,'Pedicure with gel polish.'],['Dream Spa Pedicure',55,'Aromatic soak, scrub, mineral mask, warm towels, hot stones, and a 10-minute massage.'],['Collagen Luxury Spa Pedicure',62,'Collagen soak, scrub and mask, warm towels, hot stones, and a 12-minute massage.'],['Volcano Spa Pedicure',70,'Bubbling Volcano soak, scrub, collagen mask, warm towels, hot stones, and a 15-minute massage.'],['AK Nails Signature Spa Pedicure',95,'Fresh lemon, lemongrass, ginger and rose petals; Glow Spa Collagen care, warm towels, hot stones and massage candle. 20-minute foot massage + 5-minute hand massage.']]],
['manicures','Manicures & spa combos',[
['Regular Manicure',28,'Nail shaping, cuticle care, light hand massage, regular polish.'],['Gel Manicure',38,'Nail shaping, cuticle care, light hand massage, gel polish.'],['Spa Manicure',42,'Scrub, nourishing mask, warm towels, and a 5-minute hand and forearm massage. Regular polish.'],['Dream Spa Combo',94,'Dream Pedicure + Spa Manicure.'],['Volcano Spa Combo',109,'Volcano Pedicure + Spa Manicure.']]],
['enhancements','Nail enhancements',[
['Acrylic · Full set',53,'Refill $43 cash / $43.86 card.'],['Crystal · Full set',55,'Refill $45 cash / $45.90 card.'],['Dip Powder',55,''],['Pink & White Acrylic · Full set',68,'Refill $58 cash / $59.16 card.'],['UV Gel with Polish · Full set',60,'Refill $50 cash / $51.00 card.'],['UV Gel Pink & White · Full set',75,'Refill $65 cash / $66.30 card.'],['Polygel / Hybrid Gel · Full set',65,'Refill $55 cash / $56.10 card.'],['Soft Gel Extensions (Gel-X)',60,'New set only. No refill service.']]],
['addons','Finishing touches & add-ons',[
['Nail Art',6,'','+'],['French / American',10,'','+'],['Long / Shaped',5,'','+'],['Cut Down',3,'','+'],['Nail Repair',3,'','+'],['Toe Repair',6,'','+'],['Regular Polish Change · Hands',18,''],['Gel Polish Change · Hands',28,''],['Regular Polish Change · Toes',20,''],['Gel Polish Change · Toes',30,''],['Gel Color Removal · No Service',5,''],['Acrylic Removal · With Service',10,''],['Acrylic Removal · No Service',15,''],['Foot Gel Polish Add-on',12,''],['Foot Paraffin',12,''],['Spa Manicure Gel Add-on',10,''],['Hand Paraffin',10,''],['Extra Massage · 10 min',15,'Hands or feet.'],['Extra Massage · 15 min',22,'Hands or feet.']]],
['kids','Little Angel special',[
['Manicure',17,''],['Pedicure',25,''],['Mani + Pedi',42,''],['Gel Manicure',25,''],['Gel Pedicure',33,''],['Gel Mani + Gel Pedi',58,''],['Polish Change · Hands',12,''],['Polish Change · Toes',14,'']]],
['waxing','Waxing',[
['Eyebrows',14,''],['Lips',8,''],['Chin',15,''],['Cheeks',10,''],['Sideburns',12,''],['Neck',10,''],['Underarms',25,''],['Half Arms',30,''],['Full Arms',40,'','+'],['Half Legs',40,'','+'],['Full Legs',55,'','+'],['Back & Shoulders',65,'','+'],['Fingers & Toes',10,'','+'],['Bikini',40,''],['Brazilian',65,'']]]];
const service=intro('Service','Your moment,<br><em>your way.</em>','Explore our manicures, spa pedicures, nail enhancements, and finishing touches.')+`<section class="section"><div class="category-nav">${menus.map(m=>`<a href="#${m[0]}">${m[1]}</a>`).join('')}</div><p class="service-image-note">Images illustrate service categories and nail design inspiration; your finished result will depend on your chosen service and design.</p><div class="price-note">Cash and card prices are shown. Card prices are 2% higher and apply to all credit and debit cards. Prices marked + start at the amount shown. Spa pedicures and combos include regular polish unless specified; gel and other add-ons are extra.</div>${menus.map(m=>`<section class="menu-group" id="${m[0]}"><h2>${m[1]}</h2><div class="menu-cols">${m[2].map(([name,price,description,plus=''],i)=>`<article class="menu-row"><img class="service-thumb" src="/assets/${serviceImages[m[0]][i%serviceImages[m[0]].length]}" alt="${m[0]==='waxing'?'Waxing supplies illustration':m[0]==='pedicures'?'Spa pedicure illustration':'Nail design inspiration'}" loading="lazy"><div class="service-description"><div class="menu-name">${name}</div>${description?`<p>${description}</p>`:''}</div><div class="menu-price">$${price}${plus}<small>cash</small><small>$${(price*1.02).toFixed(2)}${plus} card</small></div></article>`).join('')}</div></section>`).join('')}</section>`;
const art=intro('Art gallery','Find your next<br><em>signature.</em>','A curated collection of AI-created nail design inspiration in our signature shades. These images are concepts, rather than photographs of client work.')+`<section class="section">${gallery}<p style="color:var(--muted);font-size:14px;margin-top:35px">Bring your favorite inspiration to your appointment. Your technician can discuss the design, length, and pricing with you.</p></section>`;
const contact=intro('Contact','Come in.<br><em>Unwind.</em>','Visit AK Nails & Spa in Wilmington, Delaware. Book online or give us a call.')+`<section class="section contact-layout"><div><div class="contact-block"><p class="eyebrow">Find us</p><h3>2050 Limestone Road<br>Wilmington, DE 19808</h3><div class="contact-links"><a class="outline" href="https://www.google.com/maps/search/?api=1&query=AK+Nails+Spa+2050+Limestone+Road+Wilmington+DE+19808" target="_blank" rel="noopener">Get directions</a><a class="outline" href="tel:+13025167964">Call (302) 516-7964</a></div></div><div class="contact-block"><p class="eyebrow">Opening hours</p><table class="hours"><tbody>${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=>`<tr><td>${d}</td><td>9:00 AM – ${i<5?'7:00':i===5?'6:00':'5:00'} PM</td></tr>`).join('')}</tbody></table></div><div class="contact-block"><p class="eyebrow">Say hello</p><a class="text-link" href="mailto:aknails2050@gmail.com">aknails2050@gmail.com</a></div></div><div><img class="contact-image" src="/assets/logo-champagne.png" alt="AK Nails & Spa gold monogram and Beauty Relax Confidence slogan"><h3>Your next moment starts here.</h3><p>Choose your service and appointment time through our online booking.</p>${book}</div></section>`;
document.getElementById('app').innerHTML=`<a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/" aria-label="AK Nails & Spa home"><img src="/assets/logo-champagne.png" alt=""><div><strong>AK NAILS & SPA</strong><small>BEAUTY · RELAX · CONFIDENCE</small></div></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">${[['home','Home','/'],['service','Service','/service/'],['gallery','Art Gallery','/gallery/'],['contact','Contact','/contact/']].map(([key,label,url])=>`<a href="${url}" ${page===key?'class="active" aria-current="page"':''}>${label}</a>`).join('')}</nav>${book}</header><main id="main">${({home,service,gallery:art,contact})[page]}<section class="visit-band"><div><p class="eyebrow">A moment for you</p><h2>See you at <em>AK.</em></h2><p>2050 Limestone Road · Wilmington, DE</p></div>${book}</section></main><footer><div class="footer-top"><div><div class="footer-brand">AK NAILS & SPA</div><small>Beauty · Relax · Confidence</small></div><div class="footer-links"><a href="/service/">Service</a><a href="/gallery/">Art Gallery</a><a href="/contact/">Contact</a><a href="tel:+13025167964">(302) 516-7964</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} AK Nails & Spa</span><span>Gallery images are AI-created design inspiration.</span></div></footer><dialog id="lightbox"><button aria-label="Close image">Close</button><img alt=""><p></p></dialog>`;
const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));document.querySelector('nav').classList.toggle('open',open)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const modal=document.getElementById('lightbox');document.querySelectorAll('.art-image').forEach(button=>button.addEventListener('click',()=>{const img=button.querySelector('img');modal.querySelector('img').src=img.src;modal.querySelector('img').alt=img.alt;modal.querySelector('p').textContent=button.dataset.title+' · AI-created design inspiration';modal.showModal()}));modal.querySelector('button').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

document.querySelectorAll('.gallery-shell').forEach(shell=>{const track=shell.querySelector('.gallery-grid');const prev=shell.querySelector('.gallery-prev'),next=shell.querySelector('.gallery-next');const sync=()=>{prev.disabled=track.scrollLeft<=2;next.disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-2};const move=dir=>track.scrollBy({left:dir*(track.querySelector('.art-card').getBoundingClientRect().width+20),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));track.addEventListener('scroll',sync,{passive:true});track.addEventListener('keydown',e=>{if(e.target===track&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}});addEventListener('resize',sync);requestAnimationFrame(sync)});
